version: "3.8"
services:
  db:
    image: postgres:12
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
